### PR TITLE
Correct Annotation Attribution and Audio Recording Links

### LINKED ISSUE #1688: The tag's creator is shown instead of the tagging's creator on the recent annotations list
**Describe the bug**

When viewing the recent annotations list on a site details page, the creator of the tag is listed instead of the creator of the tagging / audio event.

**To Reproduce**

1. Go to https://www.ecosounds.org/projects/1128/sites/2981
2. Note the very old users who seemingly have recently rejoined the project...

**Expected behavior**

The creator of the audio event should be listed.

Also:

- The text for no tags on an annotation should be not be quoted (i.e. `"(no tags)"` should be `(no tags)`)
- It would be good if the link these anchors point to centered the event on the listen page (or at least applied some padding)

**Screenshots**

image

**Additional context**

https://github.com/QutEcoacoustics/workbench-client/blob/4c777a92cfbb5798cb89f682ffea0764d62b4e8a/src/app/components/sites/components/site/site.component.html#L114

### PR DESCRIPTION
**Pull request by Allcharles**
# Correct Annotation Attribution and Audio Recording Links

Fixed incorrect attribution of annotation creation, and added some links to the audio recording pages

## Issues

Closes #1688 
Relates to #984 

### Project/Region Details Page with Audio Recordings Link
image

### Site Details Page with Audio Recordings Link and fixed Annotation Attribution
image

## Final Checklist

- [ ] Assign reviewers if you have permission
- [ ] Assign labels if you have permission
- [ ] Link issues related to PR
- [ ] Ensure project linter is not producing any warnings (`npm run lint`)
- [ ] Ensure build is passing on all browsers (`npm run test:all`)
- [ ] Ensure CI build is passing
- [ ] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

### CODE REVIEW

File: src/app/components/projects/components/site-card/site-card.component.ts [hunk 1]
```diff
@@ -76,6 +82,18 @@ import { takeUntil } from "rxjs/operators";
               Visualise
             </a>
           </li>
+
+          <!-- Audio Recordings link (if recordings exist) -->
+          <li *ngIf="recording" class="nav-item">
```
Comment (atruskie) [inline src/app/components/projects/components/site-card/site-card.component.ts]: should probably just always show this link

**Review by atruskie — APPROVED** [review]
Neat, nice.
