### PR TITLE
Fix SSR contacting `/status` endpoint

### LINKED ISSUE #2120: SSR should not contact `/status` API endpoint
**Describe the bug**
SSR is currently making calls to the `/status` endpoint

Because the `/status` endpoint is a low-priority endpoint, it can hang and not give a response in the sub-second response needed for SSR rendering.

We should

- Not call the `/status` API endpoint from SSR

_This blocks the deployment of every commit after 3bc67de1d72a62d1ba4dae077df17db7439f96e4_

### PR DESCRIPTION
**Pull request by hudson-newey**
# Fix SSR contacting `/status` endpoint

SSR is currently contacting the `/status` endpoint. This is done to check if it should display the status warning icon

_I am currently manually testing to ensure that all regressions have been addressed_

## Changes

- Changed: If the website status API request times out, the [/status page](https://www.ecosounds.org/status)'s "Server Connection" status now shows "Unhealthy" instead of "Unknown"
- Bug fix: Change the website status service to not make API calls in SSR environments
- Bug fix: Change the website status icon to assume a healthy connection (to remove cumulative shift). The warning icon used to flash and disapear when the website initially loaded because it'd assume that an "undefined" response from the API (the `/status` request is pending a response), was a bad response. It now assumes that if we haven't gotten a response the API is healthy (if the `/status` request times out, the status is assumed "unhealthy" and the warning icon is shown)
- Bug fix: Previously, if the user lost internet connection, the website status service would error and API calls would stop. This would mean that when the user regained internet connection, the warning icon would not disapear. This has now been fixed.
- Upgrade Karma from version 6.4.2 -> 6.4.3

## Problems

None

## Issues

fixes: #2120

## Visual Changes

If the PR has any visual changes to the website, post pictures of the new pages and how they look. Label any images if more than one is given.

## Final Checklist

- [x] Assign reviewers if you have permission
- [x] Assign labels if you have permission
- [x] Link issues related to PR
- [x] Ensure project linter is not producing any warnings (`npm run lint`)
- [x] Ensure build is passing on all browsers (`npm run test:all`)
- [x] Ensure CI build is passing
- [x] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

### CODE REVIEW

File: src/app/components/shared/menu/website-status-indicator/website-status-indicator.component.ts [hunk 1]
```diff
@@ -1,14 +1,15 @@
...
 import { StrongRoute } from "@interfaces/strongRoute";
 import { ConfigService } from "@services/config/config.service";
+import { IS_SERVER_PLATFORM } from "src/app/app.helper";
 
 @Component({
   selector: "baw-website-status-indicator",
   template: `
     <a
-      *ngIf="!(api.status$ | async)?.isStatusHealthy"
+      *ngIf="!isSsr && !(api.status$ | async)?.isStatusHealthy"
```
Comment (atruskie) [inline src/app/components/shared/menu/website-status-indicator/website-status-indicator.component.ts]: feels complex enough to put into the class

File: src/app/components/website-status/website-status.component.ts [hunk 2]
```diff
@@ -26,30 +27,37 @@ import {
...
-    // if we want to see if the server connection is healthy, we want to negate this.model?.timedOut
-    // (so that true) means the server did not time out
-    // however, because "null" is a falsey value, negating "null" will return true (representing that the server connection is healthy)
-    // if we didn't receive a response from the server, we want to keep "null" so that we can display "Unknown" in the template
-    // we therefore need to check if the model is instantiated before we negate it
-    const serverTimeout: boolean = isInstantiated(this.model?.timedOut)
-      ? !this.model.timedOut
-      : null;
+    // if the response from the server times out, the model will be "null"
+    // if we have not revived a response from the server (a request is pending or in SSR), the model will be "undefined"
```
Comment (atruskie) [inline src/app/components/website-status/website-status.component.ts]:
```suggestion
    // if we have not received a response from the server (a request is pending or in SSR), the model will be "undefined"
```

**Review by atruskie — APPROVED** [review]
OK, 

Looks good, though I'd say we've got way too many SSR checks. 

I think you can just put it in the service and the other two components can draw from it.
