### PR TITLE
Fix verification parameter model parsing url tags

### LINKED ISSUE #2512: verification `taskTag` incorrectly cached between navigations

### PR DESCRIPTION
**Pull request by hudson-newey**
# Fix verification parameter model parsing url tags

What is the purpose of this PR?

## Changes

- Removes `tags` from verification parameter model so that there is only one source of truth for the filtered tags (now `annotationSearchParameters`)
- Refactors `tagPriority` into a `verification.component` method so that the parameter models can work independently and without knowledge of the other
- Changes verification search form component change detection strategy from `OnPush` to `Default` so that associations can resolve in the template
- Adds `searchFilters` to verification form component so that it can use the `searchFilters().tagModels` as the "tags to verify" placeholder value

## Issues

Fixes: #2512

## Visual Changes

If the PR has any visual changes to the website, post pictures of the new pages and how they look. Label any images if more than one is given.

## Final Checklist

- [ ] Assign reviewers if you have permission
- [x] Assign labels if you have permission
- [x] Link issues related to PR
- [x] Ensure project linter is not producing any warnings (`npm run lint`)
- [x] Ensure build is passing on all browsers (`npm run test:all`)
- [x] Ensure CI build is passing
- [ ] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

### CODE REVIEW

File: src/app/components/annotations/pages/verification/verification.component.ts [hunk 1]
```diff
@@ -519,8 +530,7 @@ class VerificationComponent
       verificationParameters,
     );
 
-    const urlTree = this.router.createUrlTree([], { queryParams });
-    this.location.replaceState(urlTree.toString());
+    this.router.navigate([], { queryParams });
```
[the remark this answers is not in the document]
Comment (hudson-newey) [reply src/app/components/annotations/pages/verification/verification.component.ts:538]: This is exactly what we want. I'll add a comment explaining why I haven't used `replaceUrl`

File: src/app/components/annotations/pages/verification/verification.component.ts [hunk 2]
```diff
@@ -392,6 +386,23 @@ class VerificationComponent
     }
   }
 
+  /**
+   * @description
+   * An ordered array of tag IDs representing what tags should be prioritized
+   * when displaying the tag that is being verified.
```
[the remark this answers is not in the document]
Comment (hudson-newey) [reply src/app/components/annotations/pages/verification/verification.component.ts:397]: We are using TypeScript

Using JSDoc return types adds maintenance overhead for little to no benefit over TypeScript return type annotations (which we do have)

I'm not opposed to JSDoc return documentation if it helps documenting the return type more than typing.

However, this suggested comment does not provide any additional insight over the JSDoc description section

File: src/app/components/annotations/components/verification-form/verification-form.component.html [hunk 3]
```diff
@@ -3,8 +3,8 @@
     id="task-tag-input"
     label="Tag to Verify"
     [inputPlaceholder]="
-      verificationParameters().tagModels.length > 0
-        ? $any(verificationParameters().tagModels)
+      searchParameters().tagModels.length > 0
+        ? $any(searchParameters().tagModels)
         : 'First Tag'
```
Comment (atruskie) [inline src/app/components/annotations/components/verification-form/verification-form.component.html:8]: unrelated: but 'first tag' isn't really accurate is it?

File: src/app/components/annotations/pages/verification/verification.component.ts [hunk 4]
```diff
@@ -392,6 +391,23 @@ class VerificationComponent
     }
   }
 
+  /**
+   * @description
+   * An ordered array of tag IDs representing what tags should be prioritized
```
Comment (atruskie) [inline src/app/components/annotations/pages/verification/verification.component.ts:396]:
```suggestion
   * Returns an ordered array of tag IDs representing what tags should be prioritized
```

File: src/app/components/annotations/components/verification-form/verification-form.component.html (hunk 3 above)
Comment (hudson-newey) [reply src/app/components/annotations/components/verification-form/verification-form.component.html:8]: If there is no "tag to verify" and there are no "search parameter tags", we select the first tag on the `AudioEvent` model.

I'm very happy to change the copy here because I'll admit it's not very clear

Additionally, the "Tag to verify" label is not very descriptive imo

image

I think it's easy to be confused because in my mind this sounds like the filter for what events will be shown

File: src/app/components/annotations/pages/verification/verification.component.ts (hunk 4 above)
Comment (hudson-newey) [reply src/app/components/annotations/pages/verification/verification.component.ts:396]: @copilot Open a new pull request with this change

File: src/app/components/annotations/components/verification-form/verification-form.component.html (hunk 3 above)
Comment (atruskie) [reply src/app/components/annotations/components/verification-form/verification-form.component.html:8]: But don't we have a tag priority algorithm?
