### PR TITLE
Fix: "Created" date time on Harvest list page does not show date time in users local time zone

### LINKED ISSUE #1977: harvest: upload list page created datestamp column should not show dates in UTC
From production usage:

Image

### PR DESCRIPTION
**Pull request by hudson-newey**
# Fix: "Created" date time on Harvest list page does not show date time in users local time zone

Currently, when a user uploads a Harvest, the created time will be shown in the UTC+0 time zone. The is incorrect as a it is a client side date / local date and should be shown in the users time zone.

## Changes

- Modified date formatter methods used in the Harvest list component to show all date times in the users local time zone
- Created tests to validate that the harvest created at column shows date / times in the users local time zone

_Minor Changes:_
- Created unit test bed for audio recording list component
  - This is limited to a "does create" test

## Issues

Fixes: #1977 

## Visual Changes

**Before**
image

**After**
image

_The above screenshot was taken from Brisbane, QLD (UTC+10). Therefore, all times after change are +10 hours_

## Final Checklist

- [x] Assign reviewers if you have permission
- [x] Assign labels if you have permission
- [x] Link issues related to PR
- [x] Ensure project linter is not producing any warnings (`npm run lint`)
- [ ] Ensure build is passing on all browsers (`npm run test:all`)
- [x] Ensure CI build is passing
- [ ] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

### CODE REVIEW

File: src/app/components/audio-recordings/pages/list/list.component.ts [hunk 1]
```diff
@@ -125,7 +125,7 @@ class AudioRecordingsListComponent
   }
 
   public getRecordingDate(recording: AudioRecording): string {
-    return recording.recordedDate.toFormat("yyyy-LL-dd HH:mm");
+    return recording.recordedDate.toFormat("t, cccc, d, MMMM yyyy");
```
Comment (atruskie) [inline src/app/components/audio-recordings/pages/list/list.component.ts]: the date format here was correct, revert

File: src/app/components/harvest/pages/list/list.component.ts [hunk 2]
```diff
@@ -93,7 +93,7 @@ class ListComponent extends PageComponent implements OnInit {
   }
 
   public formatDate(date: DateTime): string {
-    return date.toFormat("yyyy-MM-dd HH:mm:ss");
+    return date.toFormat("t, cccc, d, MMMM yyyy");
```
Comment (atruskie) [inline src/app/components/harvest/pages/list/list.component.ts]: revert format change

File: src/app/components/audio-recordings/pages/list/list.component.spec.ts [hunk 3]
```diff
@@ -1,24 +1,37 @@
...
+
+  it("should format dates correctly", () => {
+    const mockDateTime = DateTime.fromJSDate(
+      new Date("1995-12-17T03:24:00")
+    );
+    const mockAudioRecording = new AudioRecording({ recordedDate: mockDateTime});
+
+    const expectedDateTime = "3:24 AM, Sunday, 17, December 1995";
+
+    expect(spectator.component.getRecordingDate(mockAudioRecording)).toEqual(expectedDateTime);
```
Comment (atruskie) [inline src/app/components/audio-recordings/pages/list/list.component.spec.ts]: this test does not actually test for the problem described in #1997 - that a UTC date from the server is shown in the user's local time zone.

File: src/app/components/harvest/pages/list/list.component.spec.ts [hunk 4]
```diff
@@ -150,4 +150,15 @@ describe("ListComponent", () => {
...
+    const mockDateTime = DateTime.fromJSDate(
+      new Date("1995-12-17T03:24:00")
+    );
+    const expectedDateTime = "3:24 AM, Sunday, 17, December 1995";
+
+    setup(defaultProject, defaultHarvest);
+
+    // assert that the correct date exists
+    expect(spec.component.formatDate(mockDateTime)).toEqual(expectedDateTime);
+  });
```
Comment (atruskie) [inline src/app/components/harvest/pages/list/list.component.spec.ts]: bad test as described previously

**Review by atruskie — CHANGES_REQUESTED** [review]
OK; we use ISO8601 for all date formatting so you're going to need to change that.

Essentially, I can't see that you actually fixed the problem. Try again?

File: src/app/components/audio-recordings/pages/list/list.component.spec.ts (hunk 3 above)
Comment (hudson-newey) [reply src/app/components/audio-recordings/pages/list/list.component.spec.ts]: Ok, this seems to be a misunderstanding of the requirements. So the scope of this ticket is to not show dates provided by the server (on the Harvest list page) in the users timezone

File: src/app/components/harvest/pages/list/list.component.spec.ts [hunk 5]
```diff
@@ -150,4 +155,29 @@ describe("ListComponent", () => {
...
   }));
 
+  it("should show created dates in the users local dateTime", () => {
+    const mockUserTimeZone = "Australia/Perth"; // +08:00 UTC
+    const harvestUTCCreatedAt = DateTime.fromISO("2020-01-01T00:00:00.000Z");
+    const expectedLocalCreatedAt = "2020-01-01 08:00:00";
+    defaultHarvest = new Harvest(generateHarvest({ createdAt: harvestUTCCreatedAt }));
+
+    // To simplify tests, set the Luxon.Settings.defaultZone to a mock timezone (+08:00 UTC)
+    Settings.defaultZone = mockUserTimeZone;
```
Comment (atruskie) [inline src/app/components/harvest/pages/list/list.component.spec.ts:165]: is this reset after the test?

**Review by atruskie — APPROVED** [review]
Great! Nice and tight.

Just make sure that global luxon state is reset after the tests. If you're using a luxon test helper there's a good chance it is.

File: src/app/components/harvest/pages/list/list.component.spec.ts (hunk 5 above)
Comment (hudson-newey) [reply src/app/components/harvest/pages/list/list.component.spec.ts:165]: Thank you!

I was sure to explicitly reset the global Luxon state in the `afterEach()`

image

[here](https://github.com/QutEcoacoustics/workbench-client/pull/2029/files#diff-684d91b066ab324d51e4159d8ab8c266486c3d2800a71ea15a4def565dcfe6caR109)

**Review by atruskie — APPROVED** [review]
