### PR TITLE
Fix create/update API requests

### LINKED ISSUE #966: Remove id from update requests
Baw-server will reject requests to update a model if the models id is part of the body. To remove this issue, update the `apiUpdate` command to remove the `id` property of a model

### PR DESCRIPTION
**Pull request by Allcharles**
# Fix create/update api requests

API requests for create/update models failed due to a change in the strictness of the baw-server. This update gives us greater control over what attributes of a model will be sent on specific types of requests.

## Changes

-Added `update` and `create` properties to `bawPersistAttr` and related attribute decorators

## Problems

- Some of the updated permissions may be wrong, will have to validate as we use the website

## Issues

Fixes #966 

## Final Checklist

- [ ] Assign reviewers if you have permission
- [ ] Assign labels if you have permission
- [ ] Link issues related to PR
- [ ] Ensure project linter is not producing any warnings (`npm run lint`)
- [ ] Ensure build is passing on all browsers (`npm run test:all`)
- [ ] Ensure CI build is passing
- [ ] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

### CODE REVIEW

File: src/app/models/AbstractModel.ts [hunk 1]
```diff
@@ -138,3 +154,5 @@ export function getUnknownViewUrl(errorMsg: string) {
   console.warn(errorMsg);
   return unknownViewUrl;
 }
+
+export type ToJsonOptions = XOR<{ create: boolean }, { update: boolean }>;
```
Comment (Allcharles) [inline src/app/models/AbstractModel.ts]: Rename to `toJSONOptions`?

File: src/app/helpers/advancedTypes.ts [hunk 2]
```diff
@@ -34,3 +34,6 @@ export type KeysOfType<T, TProp> = {
 
 /** Sets type to either be T or null */
 export type Option<T> = T | null;
+
+/** Removed readonly flag from all properties in an object */
+export type Writeable<T> = {-readonly [P in keyof T]: T[P]}
```
Comment (Allcharles) [inline src/app/helpers/advancedTypes.ts]: Highlight that this only affects the types, and does not change a read-only property to a writeable one

File: src/app/models/AbstractModel.ts (hunk 1 above)
Comment (atruskie) [reply src/app/models/AbstractModel.ts]: Since this is a type I think the adverb `To` aspect of this is the more incorrect aspect. The word `Json` is also overly specific.

Maybe `ApiPersistenceOptions` ?

File: src/app/helpers/advancedTypes.ts (hunk 2 above)
Comment (atruskie) [reply src/app/helpers/advancedTypes.ts]: Also, readonly in the model, may not be the same as readonly in the API

File: src/app/models/AbstractModel.ts [hunk 3]
```diff
@@ -60,18 +67,27 @@ export abstract class AbstractModel<Model = Record<string, any>> {
...
    * Convert model to JSON
    */
-  public toJSON() {
-    const output = {};
-    this[AbstractModel.attributeKey].forEach((attribute) => {
+  public toJSON(opts?: ToJsonOptions): Partial<this> {
+    const output: Partial<Writeable<this>> = {};
+    let keys: string[];
+    if (!opts) {
+      keys = Object.keys(this).filter((key) => key !== "injector");
```
Comment (atruskie) [inline src/app/models/AbstractModel.ts:74]: does typescript have a `nameof()` construct for `"injector"`

File: src/app/models/AbstractModel.ts (hunk 1 above)
Comment (atruskie) [reply src/app/models/AbstractModel.ts]: Upon understanding the context more: `ModelSerializationOptions`?

File: src/app/models/AttributeDecorators.ts [hunk 4]
```diff
@@ -2,23 +2,42 @@ import { Id, Ids, ImageSizes, ImageUrl } from "@interfaces/apiInterfaces";
 import { DateTime, Duration } from "luxon";
 import { AbstractModel } from "./AbstractModel";
 
+function persistAttr(model: AbstractModel, key: string, opts: boolean | BawPersistAttributeOptions) {
+    model[AbstractModel.createAttributesKey] ??= [];
+    model[AbstractModel.updateAttributesKey] ??= [];
```
Comment (atruskie) [inline src/app/models/AttributeDecorators.ts:7]: could this be a static/prototypical property?
Or else done on initialization in constructor?

File: src/app/models/AbstractModel.ts (hunk 1 above)
Comment (atruskie) [reply src/app/models/AbstractModel.ts]: It also seems like this type (although cool) is overly complex.

can't the parameter just be a string literal of `"create" | "update"`?

**Review by atruskie — APPROVED** [review]
Great change.

Only questions and cosmetic changes in review.

File: src/app/models/AbstractModel.ts (hunk 1 above)
Comment (Allcharles) [reply src/app/models/AbstractModel.ts]: It appears that only types have the ability to use string literals. Afaik, it wont be a feature until at least TS4.4: https://stackoverflow.com/a/65879197/1937822

File: src/app/models/AttributeDecorators.ts (hunk 4 above)
Comment (Allcharles) [reply src/app/models/AttributeDecorators.ts:7]: Is it not already statically typed?

File: src/app/models/AbstractModel.ts (hunk 3 above)
Comment (Allcharles) [reply src/app/models/AbstractModel.ts:74]: Not sure what you mean

File: src/app/models/AttributeDecorators.ts (hunk 4 above)
Comment (atruskie) [reply src/app/models/AttributeDecorators.ts:7]: Static as in an attribute of the class/type/prototype and not the instance

File: src/app/models/AbstractModel.ts (hunk 3 above)
Comment (atruskie) [reply src/app/models/AbstractModel.ts:74]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof

https://schneidenbach.gitbooks.io/typescript-cookbook/content/nameof-operator.html

File: src/app/models/AttributeDecorators.ts (hunk 4 above)
Comment (Allcharles) [reply src/app/models/AttributeDecorators.ts:7]: Will be part of #1005
